name: CI example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      # Step 3: Install dependencies + linting tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 isort pytest

      - name: Format code with black
        run: black calculator.py tests/

      - name: Sort imports with isort
        run: isort calculator.py tests/


      - name: Run flake8
        run: |
          flake8 calculator.py tests/

      # Step 5: Run tests
      - name: Run tests
        run: |
          pytest tests/
